# Generated by Django 2.0.6 on 2018-06-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='artistinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(max_length=30, verbose_name='Name')),
                ('image', models.ImageField(upload_to='')),
                ('info', models.TextField()),
                ('genre', models.TextField()),
                ('bio_hometown', models.TextField()),
            ],
        ),
    ]
