# Generated by Django 2.0.6 on 2018-06-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artistinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('info', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='artistinfo',
        ),
    ]
