# Generated by Django 2.0.6 on 2018-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20180612_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(default='illenium.jpeg', max_length=30),
        ),
    ]
