# Generated by Django 2.0.6 on 2018-06-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_auto_20180612_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(),
        ),
    ]
