# Generated by Django 2.0.6 on 2018-06-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_artist_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='published_date',
        ),
    ]
