# Generated by Django 2.0.6 on 2018-06-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_remove_artist_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, default='illenium.jpg', upload_to=''),
        ),
    ]
