# Generated by Django 2.0.6 on 2018-06-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0015_auto_20180615_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
