# Generated by Django 2.0.6 on 2018-06-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0016_auto_20180615_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
        ),
    ]
