# Generated by Django 2.0.6 on 2018-06-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0017_auto_20180617_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='concert_date',
            field=models.DateField(null=True),
        ),
    ]
