# Generated by Django 2.0.6 on 2018-06-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0018_auto_20180617_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='post',
            name='where',
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
