# Generated by Django 2.0.6 on 2018-06-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0021_auto_20180617_0844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Concert',
        ),
    ]
