# Generated by Django 2.0.6 on 2018-06-20 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0023_concert_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofsong', models.CharField(max_length=30)),
                ('artistname', models.CharField(max_length=30)),
                ('coverimage', models.ImageField(upload_to='cover_image')),
                ('albumname', models.CharField(max_length=30)),
                ('releasedate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
